using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StockAnalyzer.Models;

/// <summary>
/// Stock recommendation data generated by the analysis engine.
/// Combines technical, fundamental, and sentiment analysis for a final recommendation.
/// </summary>
public class StockRecommendation
{
    [Key]
    public int Id { get; set; }

    /// <summary>FK to StockEmiten</summary>
    public int StockEmitenId { get; set; }

    /// <summary>Recommendation date</summary>
    public DateTime RecommendationDate { get; set; } = DateTime.UtcNow;

    // --- Component Scores (0-100) ---
    /// <summary>Technical analysis score</summary>
    public double TechnicalScore { get; set; }

    /// <summary>Fundamental analysis score</summary>
    public double FundamentalScore { get; set; }

    /// <summary>Sentiment analysis score</summary>
    public double SentimentScore { get; set; }

    // --- Combined Score ---
    /// <summary>Overall combined score (weighted average)</summary>
    public double OverallScore { get; set; }

    // --- Recommendation ---
    /// <summary>Recommendation: StrongBuy, Buy, Hold, Sell, StrongSell</summary>
    [MaxLength(20)]
    public string Recommendation { get; set; } = "Hold";

    /// <summary>Target price (12-month)</summary>
    public decimal? TargetPrice { get; set; }

    /// <summary>Stop loss price</summary>
    public decimal? StopLossPrice { get; set; }

    /// <summary>Risk level: Low, Medium, High</summary>
    [MaxLength(10)]
    public string RiskLevel { get; set; } = "Medium";

    // --- LLM Review ---
    /// <summary>LLM-generated review text</summary>
    public string? LLMReview { get; set; }

    /// <summary>Which LLM provider generated the review</summary>
    [MaxLength(50)]
    public string? LLMProvider { get; set; }

    /// <summary>LLM model used</summary>
    [MaxLength(100)]
    public string? LLMModel { get; set; }

    // --- Analysis Summary ---
    /// <summary>Key technical signals</summary>
    public string? TechnicalSummary { get; set; }

    /// <summary>Key fundamental metrics</summary>
    public string? FundamentalSummary { get; set; }

    /// <summary>Key sentiment highlights</summary>
    public string? SentimentSummary { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation property
    [ForeignKey(nameof(StockEmitenId))]
    public StockEmiten? StockEmiten { get; set; }
}

/// <summary>
/// Cached top 10 recommendation for quick access.
/// </summary>
public class TopRecommendation
{
    [Key]
    public int Id { get; set; }

    /// <summary>Rank position (1-10)</summary>
    public int Rank { get; set; }

    public int StockEmitenId { get; set; }

    [MaxLength(10)]
    public string StockCode { get; set; } = string.Empty;

    [MaxLength(200)]
    public string CompanyName { get; set; } = string.Empty;

    public double OverallScore { get; set; }

    [MaxLength(20)]
    public string Recommendation { get; set; } = "Hold";

    [MaxLength(100)]
    public string Sector { get; set; } = string.Empty;

    public DateTime GeneratedDate { get; set; } = DateTime.UtcNow;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
